// Generated by jade for the board simulation. Do not edit.
/* verilator lint_off UNUSEDSIGNAL */
/* verilator lint_off PINCONNECTEMPTY */
module jade_hw_top (
    input  wire       clk,
    input  wire [3:0] pb,
    input  wire [4:0] dipsw,
    output wire [4:0] led
);
    wire uo_txd;
    wire [4:0] uo_led;
    uart u_top (
        .clk(clk),
        .button(pb[0]),
        .rxd(1'b1),
        .txd(uo_txd),
        .led(uo_led)
    );
    assign led[0] = uo_led[0];
    assign led[1] = uo_led[1];
    assign led[2] = uo_led[2];
    assign led[3] = uo_led[3];
    assign led[4] = uo_led[4];
endmodule
